server:
  port: 8089

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 12345678
#    url: jdbc:mysql://localhost:3306/test


#sharding:
#  jdbc:
#    dataSource:
#      names: db-test0
#      db-test0: #org.apache.tomcat.jdbc.pool.DataSource
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
#        username: root
#        password: 12345678
#        maxPoolSize: 20
#    props:
#      sql:
#        show: true


#sharding.jdbc.config.sharding.tables.user.actual-data-nodes: db-test0.user_$->{0..3}
#sharding.jdbc.config.sharding.tables.user.table-strategy.standard.sharding-column: id
#sharding.jdbc.config.sharding.tables.user.table-strategy.standard.precise-algorithm-class-name: com.csp.springtest.shardingjdbc.ShardingAlgorithm.MyShardingAlgorithm


custom:
  service:
    load:
      protocol: localhost
      content: mystarter